# Dependencies
markdown:         rdiscount
highlighter:      rouge

# Permalinks
permalink:        none

# Server
destination:      _static_site
host:             127.0.0.1
port:             9001
baseurl:          /
encoding:         UTF-8
