library(igraph)
cat("Provide a Pathway to the Adjacency Matrix: ")
    pathway=readLines(con=stdin(),1)
data=read.table(pathway)
matrix=as.matrix(data)
g=graph.adjacency(matrix,weighted=TRUE)
df=get.data.frame(g)
print(df)
filename=paste("EdgeWeights",format(Sys.time(),"_%Y%m%d_%H.%M.%S"),".csv",sep="")
write.csv(df,file=filename,row.names=FALSE)
